version: "3.9"

services:
  beszel:
    image: henrygd/beszel:latest

    ports:
      - "8090:8090"

    environment:
      TZ: Asia/Ho_Chi_Minh
      BESZEL_LOG_LEVEL: debug

    volumes:
      - /home/homelab-gitops/swarm/beszel-hub/beszel-data:/data

    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

# volumes:
#   beszel-data:
