version: "3.8"

services:
  agent:
    image: portainer/agent:2.20.3
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer_net
    deploy:
      mode: global

  portainer:
    image: portainer/portainer-ee:2.20.3   # ✅ đổi CE -> EE (BE)
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - target: 9000
        published: 9000
        mode: host
      - target: 9443
        published: 9443
        mode: host
    volumes:
      - /home/homelab-gitops/swarm/portainer/portainer_data:/data                # ✅ giữ nguyên để không mất config
    networks:
      - portainer_net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == rodngo-server

networks:
  portainer_net:
    driver: overlay
    attachable: true

volumes:
  portainer_data:
    external: true